name: plot_dash
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.7.4
  - astroid=2.5.6
  - async-timeout=3.0.1
  - attrs=20.3.0
  - beautifulsoup4=4.9.3
  - boto=2.49.0
  - boto3=1.17.58
  - botocore=1.20.58
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bz2file=0.98
  - ca-certificates=2020.12.5
  - cachetools=4.2.1
  - catalogue=2.0.3
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - click=7.1.2
  - colorama=0.4.4
  - cryptography=3.4.7
  - cycler=0.10.0
  - cymem=2.0.5
  - cython-blis=0.7.4
  - dash=1.20.0
  - dash-bootstrap-components=0.12.0
  - dash-core-components=1.16.0
  - dash-daq=0.5.0
  - dash-html-components=1.1.3
  - dash-renderer=1.9.1
  - dash-table=4.11.3
  - dataclasses=0.8
  - flask=1.1.2
  - flask-caching=1.7.1
  - flask-compress=1.9.0
  - freetype=2.10.4
  - future=0.18.2
  - google-api-core=0.1.4
  - google-auth=1.28.0
  - google-cloud-core=0.28.1
  - google-cloud-storage=1.13.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.2.0
  - googleapis-common-protos=1.5.9
  - idna=2.10
  - isort=5.8.0
  - itsdangerous=1.1.0
  - jedi=0.18.0
  - jinja2=2.11.3
  - jmespath=0.10.0
  - joblib=1.0.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-aarch64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.1
  - libffi=3.3
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib=3.4.1
  - matplotlib-base=3.4.1
  - mccabe=0.6.1
  - multidict=5.1.0
  - murmurhash=1.0.5
  - ncurses=6.2
  - nltk=3.6.2
  - numpy=1.20.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - parso=0.8.2
  - pathy=0.5.2
  - pillow=8.1.2
  - pip=21.1
  - plotly=4.14.3
  - preshed=3.0.5
  - protobuf=3.15.8
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pydantic=1.7.3
  - pylint=2.7.2
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.9.2
  - python-dateutil=2.8.1
  - python-levenshtein=0.12.2
  - python_abi=3.9
  - pytz=2021.1
  - pyyaml=5.4.1
  - readline=8.1
  - regex=2021.4.4
  - requests=2.25.1
  - retrying=1.3.3
  - rsa=4.7.2
  - s3transfer=0.4.2
  - scikit-learn=0.24.2
  - scipy=1.6.3
  - selenium=3.141.0
  - setuptools=49.6.0
  - shellingham=1.4.0
  - six=1.15.0
  - smart_open=2.2.1
  - soupsieve=2.0.1
  - spacy=3.0.4
  - spacy-legacy=3.0.5
  - sqlite=3.35.5
  - srsly=2.4.1
  - thinc=8.0.3
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.60.0
  - typer=0.3.2
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2021a
  - urllib3=1.26.4
  - wasabi=0.8.2
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - annoy==1.17.0
    - en-core-web-lg==3.0.0
    - en-core-web-md==3.0.0
    - gensim==4.0.1
    - iniconfig==1.1.1
    - langdetect==1.0.7
    - pluggy==0.13.1
    - py==1.10.0
    - pytest==6.2.3
    - spacy-langdetect==0.1.2
    - wordcloud==1.8.1